OrderDeliveryWebApplication/Controllers/OrderDeliveryController.cs
using Microsoft.AspNetCore.Mvc;
using OrderDeliveryWebApplication.Domain.Models.Enums;
using OrderDeliveryWebApplication.Domain.Services;
using OrderDeliveryWebApplication.ViewModels.Mappers;
using OrderDeliveryWebApplication.ViewModels.Models.Requests;

namespace OrderDeliveryWebApplication.Controllers
{
    public class OrderDeliveryController : Controller
    {
        private readonly OrdersService _ordersService;
        
        public OrderDeliveryController(OrdersService ordersService)
        {
            _ordersService = ordersService;
        }
        
        // GET: OrderDelivery
        public async Task<IActionResult> Index()
        {
            var orders = await _ordersService.GetAllOrders();

            var responses = orders.Select(order => OrdersApiMapper.ToControllerResponse(order));
            
            return View(responses);
        }

        // GET: OrderDelivery/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var order = await _ordersService.GetOrderById(id);
            
            if (order == null)
            {
                return NotFound();
            }

            var response = OrdersApiMapper.ToControllerResponse(order);
            
            return View(response);
        }

        // GET: OrderDelivery/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OrderDelivery/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOrderControllerRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var order = OrdersApiMapper.ToDomain(request);
            
            var isSuccess = await _ordersService.CreateOrder(order);

            if (isSuccess is false)
            {
                return Problem();
            }
            
            return RedirectToAction(nameof(Index));
        }

        // GET: OrderDelivery/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var order = await _ordersService.GetOrderById(id);
            
            if (order == null)
            {
                return NotFound();
            }

            var response = OrdersApiMapper.ToUpdateRequestModel(order);
            
            return View(response);
        }

        // POST: OrderDelivery/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateOrderControllerRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var order = OrdersApiMapper.ToDomain(request, id);

            var result = await _ordersService.UpdateOrder(order);

            return result switch
            {
                UpdateOrderResult.NotFound => NotFound(),
                UpdateOrderResult.UnknownError => Problem(),
                _ => RedirectToAction(nameof(Index))
            };
        }

        // GET: OrderDelivery/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var order = await _ordersService.GetOrderById(id);
            
            if (order == null)
            {
                return NotFound();
            }

            var response = OrdersApiMapper.ToControllerResponse(order);

            return View(response);
        }

        // POST: OrderDelivery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var isSuccess = await _ordersService.DeleteOrder(id);
            
            if (isSuccess is false)
            {
                return Problem();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

OrderDeliveryWebApplication/Views/OrderDelivery/Create.cshtml
@model OrderDeliveryWebApplication.ViewModels.Models.Requests.CreateOrderControllerRequest

@{
    ViewData["Title"] = "Создание заказа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Новый заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SenderCity" class="control-label"></label>
                <input asp-for="SenderCity" class="form-control" />
                <span asp-validation-for="SenderCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenderAddress" class="control-label"></label>
                <input asp-for="SenderAddress" class="form-control" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientCity" class="control-label"></label>
                <input asp-for="RecipientCity" class="form-control" />
                <span asp-validation-for="RecipientCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientAddress" class="control-label"></label>
                <input asp-for="RecipientAddress" class="form-control" />
                <span asp-validation-for="RecipientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoWeight" class="control-label"></label>
                <input asp-for="CargoWeight" class="form-control" />
                <span asp-validation-for="CargoWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PickUpDate" class="control-label"></label>
                <input asp-for="PickUpDate" class="form-control" />
                <span asp-validation-for="PickUpDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку заказов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrderDeliveryWebApplication/Views/OrderDelivery/Delete.cshtml
@model OrderDeliveryWebApplication.ViewModels.Models.Responses.OrderControllerResponse;

@{
    ViewData["Title"] = "Удаление заказа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Вы действительно хотите удалить этот заказ?</h3>
<div>
    <h4>Удаление заказа</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CargoWeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CargoWeight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PickUpDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PickUpDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад к списку заказов</a>
    </form>
</div>

OrderDeliveryWebApplication/Views/OrderDelivery/Details.cshtml
@model OrderDeliveryWebApplication.ViewModels.Models.Responses.OrderControllerResponse; 
@{
    ViewData["Title"] = "Детали заказа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Информация о заказе</h4>
    <hr/>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SenderAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SenderAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientCity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientCity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RecipientAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecipientAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CargoWeight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CargoWeight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PickUpDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PickUpDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Назад к списку заказов</a>
</div>

OrderDeliveryWebApplication/Views/OrderDelivery/Edit.cshtml
@model OrderDeliveryWebApplication.ViewModels.Models.Requests.UpdateOrderControllerRequest; 

@{
    ViewData["Title"] = "Редактирование заказа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Редактирование</h1>

<h4>Мой заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="SenderCity" class="control-label"></label>
                <input asp-for="SenderCity" class="form-control" />
                <span asp-validation-for="SenderCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SenderAddress" class="control-label"></label>
                <input asp-for="SenderAddress" class="form-control" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientCity" class="control-label"></label>
                <input asp-for="RecipientCity" class="form-control" />
                <span asp-validation-for="RecipientCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipientAddress" class="control-label"></label>
                <input asp-for="RecipientAddress" class="form-control" />
                <span asp-validation-for="RecipientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CargoWeight" class="control-label"></label>
                <input asp-for="CargoWeight" class="form-control" />
                <span asp-validation-for="CargoWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PickUpDate" class="control-label"></label>
                <input asp-for="PickUpDate" class="form-control" />
                <span asp-validation-for="PickUpDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить изменения" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к сиску заказов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrderDeliveryWebApplication/Views/OrderDelivery/Index.cshtml
@model IEnumerable<OrderDeliveryWebApplication.ViewModels.Models.Responses.OrderControllerResponse>

@{
    ViewData["Title"] = "Заказы";
}

<h1>Мои заказы</h1>

<p>
    <a asp-action="Create">Создать новый заказ</a>
</p>
<table id="ordersTable">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SenderCity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SenderAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecipientCity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecipientAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CargoWeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickUpDate)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr onclick="location.href='@Url.Action($"Details", "OrderDelivery", new{Id = item.Id})'">
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SenderCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SenderAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipientCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipientAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CargoWeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PickUpDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
    </tbody>
</table>